# Generated by Django 5.1.1 on 2024-09-16 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unversity', '0004_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unversity.group')),
            ],
        ),
    ]
